#设置端口号
server:
  port: 8005

spring:
  application:
    name: cloud-feign-recive

eureka:
  client:
    register-with-eureka: true
    #表示自己是注册中心，职责是维护服务实例，不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server7001交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka,http://localhost:7003/eureka,http://localhost:7004/eureka
  instance:
    #应用端口名
    instance-id: payment8005
    #以ip地址注册到服务中心，相互注册使用ip地址
    prefer-ip-address: true
    #eureka客户端发送心跳时间间隔，默认30s
    # lease-renewal-interval-in-seconds: 30
    #eureka服务端在收到最后一次心跳等待时间上线，默认90s
    # lease-expiration-duration-in-seconds: 2
#    appname: cloud-payment-previde
    #负载均衡规则
    #sping-boot-recive:
    #ribbon:
    # NFLoadBalancerRuleClassName:com.netflix.loadbalancer.RandomRule
