#设置端口号
server:
  port: 9527
#应用服务名
spring:
  application:
    name: cloud-getway-recive9527
  cloud:
    #开启从注册中心动态获取路由功能，利用微服务名进行路由
    gateway:
      discovery:
        locator:
          enabled: true
          #gatway网关配置
      routes:
        #前面有-是集合
        #路由的ID，没有固定的规则但要求唯一
        - id: payment_routh
        #匹配成功后的提供服务的地址
          uri: lb://CLOUD-PAYMENT-RECIVE #集群配置的地址
#          断言，路径相同的匹配路由
          predicates:
           - Path=/finding/**
#           - Cookie= username,ss
        #路由的ID，没有固定的规则但要求唯一
        - id: payment_routh1
        #匹配成功后的提供服务的地址
          #CLOUD-PAYMENT-RECIVE提供者名字
          uri: lb://CLOUD-PAYMENT-RECIVE
          predicates:
            #断言
            - Path=/finding/**
#            在这个时间点之后运行
#            - After= 2021-11-16T16:25:29.301+08:00[Asia/Shanghai]
#            - Cookie= username,ss


#eureka相关配置
eureka:
  client:
    register-with-eureka: true
    #表示自己是注册中心，职责是维护服务实例，不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server7001交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka
  instance:
    #应用端口名
    instance-id: getway9527
    #以ip地址注册到服务中心，相互注册使用ip地址
    prefer-ip-address: true