#设置端口号
server:
  port: 8089

spring:
  #服务名称
  application:
    name: cloud-payment-recive
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.76.131/th?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTime=Asia/Shanghai
    username: root
    password: root123

eureka:
  client:
    register-with-eureka: true
    #表示自己是注册中心，职责是维护服务实例，不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server7001交互的地址查询服务和注册服务都需要依赖这个地址
      #eureka地址信息
      defaultZone: http://localhost:7001/eureka,http://localhost:7003/eureka,http://localhost:7004/eureka
  instance:
    #应用端口名
    instance-id: payment8089
    #以ip地址注册到服务中心，相互注册使用ip地址
    prefer-ip-address: true
    #注册中心的application列，是对一个微服务的统称
#    appname: cloud-payment-recive
    #eureka客户端发送心跳时间间隔，默认30s
   # lease-renewal-interval-in-seconds: 30
    #eureka服务端在收到最后一次心跳等待时间上线，默认90s
   # lease-expiration-duration-in-seconds: 2
 # server:
    #关闭自我保护机制,保证不可用服务被剔除
    #enable-self-preservation: flase
    #清理吴小姐点的时间间隔
    #eviction-interval-timer-in-ms:2000
#设置客户端超时时间
ribbon:
  #建立连接后从服务器读取到可用资源所用的时间
  ReadTimeOut: 50000
  #建立连接所用时间，适用于网络正常两端连接的时间
  ConnectTimeout: 50000