#设置端口号
server:
  port: 8007


spring:
  application:
    name: spring-htstrix-recive


eureka:
  client:
    register-with-eureka: true
    #表示自己是注册中心，职责是维护服务实例，不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server7001交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka
  instance:
    #应用端口名
    instance-id: payment8007
    #以ip地址注册到服务中心，相互注册使用ip地址
    prefer-ip-address: true
#设置客户端超时时间
ribbon:
  #建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 18000
  #建立连接所用时间，适用于网络正常两端连接的时间
  ConnectTimeout: 18000
  #开启hystrix
feign:
  hystrix:
    enabled: true
#系统默认是1s所以需要更改，系统默认取最小值
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000